import {existsSync, mkdirSync, readFileSync, writeFileSync} from 'node:fs'
import {join, resolve} from 'node:path'
import type {Registry} from '../registry-types.js'
import type {CommandResult} from './lookup.js'
import {lookup} from '../registry.js'
import {suggestions} from '../search.js'

/*
 * duro mockup — token-seeded artboards, and the check that makes one a
 * handoff contract.
 *
 * A mockup drawn outside the token system has to be TRANSLATED into the
 * design system when it is implemented, and every translation drifts (the
 * gate-board mockup of 2026-09 used 158 hex literals, 15 of them in the
 * palette). `seed` writes an artboard whose only design vocabulary is the
 * resolved token block, so the artboard is written in token names from the
 * first line; `check` refuses an artboard that reaches past them, and refuses
 * one that does not say which design-system component each control is.
 *
 * What binds when a direction is chosen: layout, hierarchy, states, the
 * data-duro component map and the token names. What does not: the artboard's
 * pixel geometry — widths, heights and positions are not tokens and are not
 * checked.
 */

export const TOKENS_START = '/* duro:tokens start */'
export const TOKENS_END = '/* duro:tokens end */'

/** The artboard size the design canvas expects on the root element. */
export const ARTBOARD_WIDTH = 1120
export const ARTBOARD_HEIGHT = 840

export const MOCKUP_THEMES = ['dark', 'light', 'high-contrast'] as const
export type MockupTheme = (typeof MOCKUP_THEMES)[number]

export interface SeedOptions {
  /** Directory to write into. Defaults to docs/mockups/<name>. */
  out?: string
  /** Artboard file stem. The design canvas needs one called Main. */
  name?: string
  theme?: string
  cwd?: string
}

export interface CheckOptions {
  cwd?: string
}

export interface Finding {
  file: string
  line: number
  rule:
    | 'raw-color'
    | 'raw-length'
    | 'raw-breakpoint'
    | 'unknown-component'
    | 'no-component-map'
    | 'unannotated-control'
  message: string
}

// ---------------------------------------------------------------------------
// seed

/**
 * The artboard skeleton, in the shape the `design` skill's canvas expects:
 * support.js verbatim, one <x-dc>, one <helmet><style>. Everything a
 * finished artboard adds goes inside the same style block and the root div.
 */
export function seedArtboard(registry: Registry, name: string, theme: MockupTheme): string {
  const themeAttr = theme === 'dark' ? '' : ` data-theme="${theme}"`
  const tokens = registry.tokens.mockupCss.trimEnd()
  return `<!doctype html>
<html${themeAttr}>
<head>
  <meta charset="utf-8">
  <script src="./support.js"></script>
</head>
<body>
<x-dc>
<helmet>
  <style>
${TOKENS_START}
${tokens}
${TOKENS_END}

/*
 * ${name} — a Duro mockup artboard. GENERATED by \`duro mockup seed\`.
 *
 * Every colour, spacing, radius, font, shadow and duration below is a
 * var(--duro-*) from the block above — never a literal. Geometry (widths,
 * heights, positions) is free. Every element a person can act on carries
 * data-duro="<Component>" or data-duro="<Component>.<Part>" naming the
 * @duro-app/ui component that will implement it (duro list components).
 * \`duro mockup check ${name}.dc.html\` enforces both.
 */
body {
  margin: 0;
  background: var(--duro-color-bg);
  color: var(--duro-color-text);
  font-family: var(--duro-typography-font-family);
  font-size: var(--duro-typography-font-size-md);
  line-height: var(--duro-typography-line-height);
}
.artboard {
  width: ${ARTBOARD_WIDTH}px;
  height: ${ARTBOARD_HEIGHT}px;
  overflow: hidden;
  padding: var(--duro-spacing-lg);
  box-sizing: border-box;
}
  </style>
</helmet>
<div class="artboard">
  <!--
    Vocabulary (delete this comment when the artboard is authored):
      <div data-duro="PageShell"> … </div>
      <button data-duro="Button variant=primary">Save</button>
      <div data-duro="Tabs"> <div data-duro="Tabs.List"> <div data-duro="Tabs.Tab">…</div> </div> </div>
      <div data-duro="Table"> … </div>
      <span data-duro="Badge variant=success">Granted</span>
    Props after the name are notes for the implementer, not checked.
  -->
</div>
</x-dc>
</body>
</html>
`
}

export function runMockupSeed(registry: Registry, options: SeedOptions = {}): CommandResult {
  const cwd = options.cwd ?? process.cwd()
  const name = options.name ?? 'Main'
  if (!/^[A-Za-z][A-Za-z0-9-]*$/.test(name)) {
    return usage(`duro mockup seed: --name must be a bare file stem, got "${name}"`)
  }
  const theme = (options.theme ?? 'dark') as MockupTheme
  if (!MOCKUP_THEMES.includes(theme)) {
    return usage(
      `duro mockup seed: --theme must be one of ${MOCKUP_THEMES.join(' | ')}, got "${theme}"`,
    )
  }
  const dir = options.out ?? join('docs', 'mockups', name.toLowerCase())
  const path = join(dir, `${name}.dc.html`)
  const abs = resolve(cwd, path)
  if (existsSync(abs)) {
    return {
      text: `duro mockup seed: ${path} exists — pick another --name or --out, or delete it`,
      data: {kind: 'exists', path},
      exitCode: 1,
    }
  }
  mkdirSync(resolve(cwd, dir), {recursive: true})
  writeFileSync(abs, seedArtboard(registry, name, theme), 'utf8')
  return {
    text: [
      `Seeded ${path} (${theme}).`,
      'Author it with var(--duro-*) values and data-duro component names only,',
      `then: duro mockup check ${path}  (an unauthored seed fails on no-component-map alone)`,
    ].join('\n'),
    data: {ok: true, path, theme},
  }
}

// ---------------------------------------------------------------------------
// check

/** CSS properties whose values are design tokens in this system. */
const SPACING_PROPS =
  /^(padding|margin|gap|row-gap|column-gap|inset|padding-[a-z-]+|margin-[a-z-]+)$/
const RADIUS_PROPS = /^border(-[a-z]+-[a-z]+)?-radius$/
const TYPE_PROPS = /^(font-size|font-weight|font-family|font)$/
const SHADOW_PROPS = /^box-shadow$/
const MOTION_PROPS =
  /^(transition|transition-duration|transition-timing-function|animation|animation-duration|animation-timing-function)$/

const COLOR_LITERAL = /#[0-9a-fA-F]{3,8}\b|\b(?:rgba?|hsla?)\(/g
const LENGTH_LITERAL = /(?<![\w.-])(\d*\.?\d+)(px|rem|em|ms|s)\b/g
const WEIGHT_LITERAL = /(?<![\w.-])([1-9]00)\b/
const BREAKPOINT_QUERY =
  /@(?:media|container)[^{]*?\(\s*(?:min|max)-(?:width|height)\s*:\s*(\d+)px\s*\)/g

/** Native controls — a duro component exists for each; an artboard names it. */
const NATIVE_CONTROLS = new Set(['button', 'input', 'select', 'textarea', 'a', 'table', 'dialog'])
const VOID_ELEMENTS = new Set([
  'area',
  'base',
  'br',
  'col',
  'embed',
  'hr',
  'img',
  'input',
  'link',
  'meta',
  'source',
  'track',
  'wbr',
])

function usage(text: string): CommandResult {
  return {text, data: {kind: 'usage-error'}, exitCode: 2}
}

function lineOf(source: string, index: number): number {
  let line = 1
  for (let i = 0; i < index && i < source.length; i++) if (source[i] === '\n') line++
  return line
}

/** Blank out the token block so its literals are never scanned, keeping offsets. */
function maskTokenBlock(source: string): string {
  const start = source.indexOf(TOKENS_START)
  if (start < 0) return source
  const end = source.indexOf(TOKENS_END, start)
  if (end < 0) return source
  const stop = end + TOKENS_END.length
  return (
    source.slice(0, start) + source.slice(start, stop).replace(/[^\n]/g, ' ') + source.slice(stop)
  )
}

/** Blank out comments and var(...) references, keeping offsets. */
function maskInert(css: string): string {
  return css
    .replace(/\/\*[\s\S]*?\*\//g, (m) => m.replace(/[^\n]/g, ' '))
    .replace(/var\([^)]*\)/g, (m) => ' '.repeat(m.length))
}

interface Declaration {
  prop: string
  value: string
  /** Offset of the value in the whole file. */
  at: number
}

/** Every `prop: value` in a CSS text, with file offsets. Braces are ignored. */
function declarations(css: string, base: number): Declaration[] {
  const out: Declaration[] = []
  const re = /([a-zA-Z-]+)\s*:\s*([^;{}]+)/g
  let m: RegExpExecArray | null
  while ((m = re.exec(css))) {
    const prop = m[1].toLowerCase()
    // `a:hover`, `@media (min-width: …)` and URLs are not declarations.
    if (prop.startsWith('-') || (m.index > 0 && /[(@:]/.test(css[m.index - 1] ?? ''))) continue
    out.push({prop, value: m[2], at: base + m.index + m[0].indexOf(m[2])})
  }
  return out
}

function scanCss(
  file: string,
  source: string,
  css: string,
  base: number,
  findings: Finding[],
): void {
  const inert = maskInert(css)

  // Colors: a literal is never right, on any property.
  for (const m of inert.matchAll(COLOR_LITERAL)) {
    findings.push({
      file,
      line: lineOf(source, base + (m.index ?? 0)),
      rule: 'raw-color',
      message: `'${m[0].replace(/\($/, '')}' is a raw colour — use a var(--duro-color-*) from the token block`,
    })
  }

  // Breakpoints: media queries cannot read a variable, so a literal is
  // allowed — but only one from the scale.
  const scale = breakpointScale()
  for (const m of inert.matchAll(BREAKPOINT_QUERY)) {
    if (!scale.has(Number(m[1]))) {
      findings.push({
        file,
        line: lineOf(source, base + (m.index ?? 0)),
        rule: 'raw-breakpoint',
        message: `${m[1]}px is not a breakpoint — the scale is ${[...scale].join(' / ')}px`,
      })
    }
  }

  for (const {prop, value, at} of declarations(inert, base)) {
    const hint = SPACING_PROPS.test(prop)
      ? '--duro-spacing-*'
      : RADIUS_PROPS.test(prop)
        ? '--duro-radius-*'
        : TYPE_PROPS.test(prop)
          ? '--duro-typography-* / --duro-type-scale-*'
          : SHADOW_PROPS.test(prop)
            ? '--duro-shadow-*'
            : MOTION_PROPS.test(prop)
              ? '--duro-duration-* / --duro-easing-*'
              : null
    if (!hint) continue
    const hit = value.match(LENGTH_LITERAL)?.find((l) => !/^0(px|rem|em|ms|s)$/.test(l))
    const weight =
      prop === 'font-weight' || prop === 'font' ? value.match(WEIGHT_LITERAL)?.[1] : null
    const literal = hit ?? weight
    if (literal) {
      findings.push({
        file,
        line: lineOf(source, at),
        rule: 'raw-length',
        message: `${literal} on \`${prop}\` is a raw value — use a var(${hint}) token`,
      })
    }
  }
}

let cachedScale: Set<number> | null = null
function breakpointScale(): Set<number> {
  return (cachedScale ??= new Set([480, 640, 768, 1024, 1280]))
}

function resolveComponent(registry: Registry, spec: string): string | null {
  // "Button variant=primary" → Button; "Tabs.Tab" → Tabs + part Tab.
  const head = spec.trim().split(/\s+/)[0] ?? ''
  const [name, part] = head.split('.')
  const hit = lookup(registry, name)
  if (!hit || (hit.kind !== 'component' && hit.kind !== 'recipe'))
    return `unknown component "${name}"`
  if (part && hit.kind === 'component') {
    const parts = hit.entry.parts
    if (!parts) return `${hit.key} has no parts — drop ".${part}"`
    if (!parts[part]) return `${hit.key} has no part "${part}" (${Object.keys(parts).join(', ')})`
  }
  return null
}

interface OpenTag {
  tag: string
  annotated: boolean
}

function scanMarkup(file: string, source: string, findings: Finding[], registry: Registry): void {
  // The markup is what is left once <style> blocks are blanked.
  const blank = (m: string): string => m.replace(/[^\n]/g, ' ')
  const html = source
    .replace(/<style\b[\s\S]*?<\/style>/gi, blank)
    .replace(/<!--[\s\S]*?-->/g, blank)
  const styleBlocks = [...source.matchAll(/<style\b[^>]*>([\s\S]*?)<\/style>/gi)]

  // Classes whose rules read like a control, so a styled div that uses one
  // has to be named. A control in a canvas artboard is rarely a <button>: it
  // is a div with a pointer cursor, a hover state, or the padded rounded
  // filled look of a button/chip/row. The signature is the UNION over every
  // rule that mentions the class — `.btn{padding;border-radius}` and
  // `.btn.pri{background}` together make `btn` a control.
  const traits = new Map<string, Set<string>>()
  const trait = (cls: string, t: string): void => {
    const set = traits.get(cls) ?? new Set<string>()
    set.add(t)
    traits.set(cls, set)
  }
  for (const block of styleBlocks) {
    const css = maskInert(maskTokenBlock(block[1]))
    for (const rule of css.matchAll(/([^{}]+)\{([^{}]*)\}/g)) {
      const [, selector, body] = rule
      const classes = [...selector.matchAll(/\.([A-Za-z_][\w-]*)/g)].map((m) => m[1])
      for (const cls of classes) {
        if (/cursor\s*:\s*pointer/.test(body)) trait(cls, 'pointer')
        if (/:(hover|active|focus)/.test(selector)) trait(cls, 'state')
        if (/border-radius\s*:/.test(body)) trait(cls, 'radius')
        if (/padding(-[a-z]+)?\s*:/.test(body)) trait(cls, 'padding')
        if (/background(-color)?\s*:/.test(body)) trait(cls, 'fill')
      }
    }
  }
  const controlClasses = new Set(
    [...traits]
      .filter(
        ([, t]) =>
          t.has('pointer') ||
          t.has('state') ||
          (t.has('radius') && t.has('padding') && t.has('fill')),
      )
      .map(([cls]) => cls),
  )

  const stack: OpenTag[] = []
  let annotatedCount = 0
  const tagRe = /<\/?([a-zA-Z][\w-]*)([^>]*)>/g
  let m: RegExpExecArray | null
  while ((m = tagRe.exec(html))) {
    const [whole, rawTag, attrs] = m
    const tag = rawTag.toLowerCase()
    if (whole.startsWith('</')) {
      // Pop to the matching open tag; tolerate stray closes.
      const i = stack.map((t) => t.tag).lastIndexOf(tag)
      if (i >= 0) stack.length = i
      continue
    }
    const duro = attrs.match(/\bdata-duro\s*=\s*"([^"]*)"|\bdata-duro\s*=\s*'([^']*)'/)
    const spec = duro ? (duro[1] ?? duro[2] ?? '') : null
    const line = lineOf(source, m.index)
    let annotated = false
    if (spec !== null) {
      annotatedCount++
      annotated = true
      const problem = resolveComponent(registry, spec)
      if (problem) {
        const head = spec.trim().split(/[\s.]/)[0] ?? ''
        const near = suggestions(registry, head).slice(0, 3)
        findings.push({
          file,
          line,
          rule: 'unknown-component',
          message: `data-duro="${spec}": ${problem}${near.length ? ` — did you mean ${near.join(', ')}?` : ''}`,
        })
      }
    }

    const classes = attrs.match(/\bclass\s*=\s*"([^"]*)"|\bclass\s*=\s*'([^']*)'/)
    const classList = (classes?.[1] ?? classes?.[2] ?? '').split(/\s+/).filter(Boolean)
    const inline = attrs.match(/\bstyle\s*=\s*"([^"]*)"|\bstyle\s*=\s*'([^']*)'/)
    const inlineCss = inline?.[1] ?? inline?.[2] ?? ''
    if (inlineCss) {
      const at = m.index + whole.indexOf(inlineCss)
      scanCss(file, source, inlineCss, at, findings)
    }
    // A styled control must name itself: a named parent never covers a child
    // that draws like a control, or naming the list once would excuse every
    // row. The parent covers only a bare native control inside it (the ×
    // button of a Tag, the input of a Combobox).
    const styledControl =
      /\b(role|tabindex)\s*=/.test(attrs) ||
      /cursor\s*:\s*pointer/.test(inlineCss) ||
      classList.some((c) => controlClasses.has(c))
    const parent = stack[stack.length - 1]
    const unnamed =
      !annotated && (styledControl || (NATIVE_CONTROLS.has(tag) && !parent?.annotated))
    if (unnamed) {
      findings.push({
        file,
        line,
        rule: 'unannotated-control',
        message: `<${tag}${classList.length ? ` class="${classList.join(' ')}"` : ''}> reads as a control but names no design-system component — add data-duro="<Component>" (duro list components)`,
      })
    }

    const selfClosing = VOID_ELEMENTS.has(tag) || whole.endsWith('/>')
    if (!selfClosing) stack.push({tag, annotated})
  }

  if (annotatedCount === 0) {
    findings.push({
      file,
      line: 1,
      rule: 'no-component-map',
      message:
        'no data-duro attribute anywhere — an artboard names the design-system component behind every control, or it cannot be implemented from',
    })
  }
}

/** Every finding for one artboard's HTML. Exported for the MCP tool and tests. */
export function checkArtboard(registry: Registry, file: string, source: string): Finding[] {
  const findings: Finding[] = []
  const masked = maskTokenBlock(source)
  for (const block of masked.matchAll(/<style\b[^>]*>([\s\S]*?)<\/style>/gi)) {
    const at = (block.index ?? 0) + block[0].indexOf(block[1])
    scanCss(file, source, block[1], at, findings)
  }
  scanMarkup(file, masked, findings, registry)
  findings.sort((a, b) => a.line - b.line || a.rule.localeCompare(b.rule))
  return findings
}

export function runMockupCheck(
  registry: Registry,
  files: string[],
  options: CheckOptions = {},
): CommandResult {
  if (files.length === 0) return usage('duro mockup check: give at least one <file.dc.html>')
  const cwd = options.cwd ?? process.cwd()
  const all: Finding[] = []
  for (const file of files) {
    let source: string
    try {
      source = readFileSync(resolve(cwd, file), 'utf8')
    } catch {
      return {
        text: `duro mockup check: cannot read ${file}`,
        data: {kind: 'not-found', file},
        exitCode: 2,
      }
    }
    all.push(...checkArtboard(registry, file, source))
  }
  const lines = all.map((f) => `${f.file}:${f.line} ${f.rule}: ${f.message}`)
  if (all.length === 0) {
    return {
      text: `duro mockup check: ${files.length} artboard(s) speak tokens and name their components`,
      data: {ok: true, files, findings: []},
    }
  }
  return {
    text: `duro mockup check: ${all.length} finding(s)\n${lines.join('\n')}`,
    data: {ok: false, files, findings: all},
    exitCode: 1,
  }
}

const SUBCOMMANDS = ['seed', 'check']

export function runMockup(
  registry: Registry,
  sub: string | undefined,
  rest: string[],
  options: SeedOptions & CheckOptions,
): CommandResult {
  if (sub === 'seed') {
    if (rest.length > 0) return usage('duro mockup seed takes flags only (--out, --name, --theme)')
    return runMockupSeed(registry, options)
  }
  if (sub === 'check') return runMockupCheck(registry, rest, options)
  return usage(
    `duro mockup: unknown subcommand "${sub ?? ''}" — expected ${SUBCOMMANDS.join(' | ')}`,
  )
}
