// Builds the mockup stylesheet text from the token sources. Pure: reads
// src/**/*.css.ts, returns a string. Used by generate-mockup-css.mjs (writes
// dist/mockup.css) and by packages/cli/scripts/build-registry.mjs (embeds it
// in registry.json so `duro mockup seed` needs no tokens build).

import {join} from 'node:path'
import {extractCallArg} from './literals.mjs'

export function buildMockupCss(srcDir) {
  // Same aliases as generate-vars-css.mjs — the two files publish ONE name set.
  const GROUP_NAMES = {
    colors: 'color',
    radii: 'radius',
    shadows: 'shadow',
    spacing: 'spacing',
    layoutSpacing: 'layout-spacing',
    typography: 'typography',
    typeScale: 'type-scale',
    duration: 'duration',
    easing: 'easing',
    breakpoints: 'breakpoint',
  }

  const kebab = (s) =>
    s
      .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
      .replace(/([A-Z]+)([A-Z][a-z])/g, '$1-$2')
      .toLowerCase()

  const tokensDir = join(srcDir, 'tokens')
  const themesDir = join(srcDir, 'themes')
  const vars = (file, exportName) =>
    extractCallArg(join(tokensDir, file), 'defineVars', 0, exportName)
  const theme = (file, exportName) =>
    extractCallArg(join(themesDir, file), 'createTheme', 1, exportName)

  // Theme-independent scales, declared once on :root and inherited everywhere.
  const shared = {
    spacing: vars('spacing.css.ts', 'spacing'),
    radii: vars('spacing.css.ts', 'radii'),
    layoutSpacing: vars('layout-spacing.css.ts', 'layoutSpacing'),
    typography: vars('typography.css.ts', 'typography'),
    typeScale: vars('typography.css.ts', 'typeScale'),
    duration: vars('motion.css.ts', 'duration'),
    easing: vars('motion.css.ts', 'easing'),
    breakpoints: extractCallArg(
      join(tokensDir, 'breakpoints.css.ts'),
      'defineConsts',
      0,
      'breakpoints',
    ),
  }

  // What changes per theme. `:root` is the base (dark) palette; the data-theme
  // attribute is what ThemeProvider stamps, so a seeded artboard switches theme
  // by setting it on <html>.
  const THEMES = [
    {
      selector: ':root',
      scheme: 'dark',
      colors: vars('colors.css.ts', 'colors'),
      shadows: vars('shadows.css.ts', 'shadows'),
    },
    {
      selector: ':root[data-theme="light"]',
      scheme: 'light',
      colors: theme('light.css.ts', 'lightTheme'),
      shadows: theme('light.css.ts', 'lightShadows'),
    },
    {
      selector: ':root[data-theme="high-contrast"]',
      scheme: 'dark',
      colors: theme('high-contrast.css.ts', 'highContrastTheme'),
      shadows: theme('high-contrast.css.ts', 'highContrastShadows'),
    },
  ]

  function declarations(group, bag) {
    const alias = GROUP_NAMES[group]
    const lines = [`  /* ${group} */`]
    for (const [name, value] of Object.entries(bag).sort(([a], [b]) => a.localeCompare(b))) {
      lines.push(`  --duro-${alias}-${kebab(name)}: ${value};`)
    }
    return lines
  }

  let count = 0
  const blocks = []

  for (const {selector, scheme, colors, shadows} of THEMES) {
    const lines = [`${selector} {`, `  color-scheme: ${scheme};`]
    lines.push(...declarations('colors', colors), ...declarations('shadows', shadows))
    if (selector === ':root') {
      for (const [group, bag] of Object.entries(shared)) lines.push(...declarations(group, bag))
    }
    count += lines.filter((l) => l.startsWith('  --duro-')).length
    lines.push('}')
    blocks.push(lines.join('\n'))
  }

  const css = `/*
 * GENERATED by scripts/generate-mockup-css.mjs — do not edit.
 *
 * The design tokens as resolved values, for HTML that loads no stylesheet
 * (mockup artboards, static previews). Same names as vars.css; where vars.css
 * follows the live theme, this file carries every theme and switches on
 * <html data-theme="light|high-contrast">.
 *
 * Inside the component library and the apps, never use this: go through
 * css.create() and the token imports, or vars.css from plain CSS.
 */
${blocks.join('\n\n')}
`

  return {css, count}
}
