import {css} from 'react-strict-dom'
import {colors, radii, spacing, typography, shadows} from '@duro-app/tokens'

export const styles = css.create({
  root: {
    position: 'relative',
    display: 'inline-flex',
  },
  trigger: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
    paddingTop: spacing.sm,
    paddingBottom: spacing.sm,
    paddingLeft: spacing.md,
    paddingRight: spacing.md,
    fontFamily: typography.fontFamily,
    fontSize: typography.fontSizeSm,
    color: colors.text,
    backgroundColor: colors.bgCard,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: {
      default: colors.border,
      ':hover': colors.accent,
    },
    borderRadius: radii.sm,
    cursor: 'pointer',
    transitionProperty: 'border-color',
    transitionDuration: '150ms',
  },
  value: {
    color: colors.text,
  },
  placeholder: {
    color: colors.textMuted,
  },
  icon: {
    display: 'flex',
    alignItems: 'center',
    color: colors.textMuted,
  },
  backdrop: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 49,
  },
  popup: {
    position: 'absolute',
    top: '100%',
    left: 0,
    marginTop: spacing.xs,
    backgroundColor: colors.bgCard,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: colors.border,
    borderRadius: radii.sm,
    boxShadow: shadows.md,
    paddingTop: spacing.xs,
    paddingBottom: spacing.xs,
    minWidth: 120,
    zIndex: 50,
  },
  item: {
    display: 'flex',
    alignItems: 'center',
    paddingTop: spacing.sm,
    paddingBottom: spacing.sm,
    paddingLeft: spacing.md,
    paddingRight: spacing.md,
    fontSize: typography.fontSizeSm,
    fontFamily: typography.fontFamily,
    color: colors.text,
    borderRadius: radii.sm,
    cursor: 'pointer',
    backgroundColor: 'transparent',
    transitionProperty: 'background-color',
    transitionDuration: '150ms',
  },
  itemSelected: {
    color: colors.accent,
    fontWeight: typography.fontWeightMedium,
  },
  itemHighlighted: {
    backgroundColor: colors.bgCardHover,
  },
  hidden: {
    display: 'none',
  },
})
