/**
 * The generated Claude Code SessionStart hook, and the wiring it needs.
 *
 * Kept as data (not prose in a README) so `duro hook install` can write it and
 * `duro hook install --check` can byte-compare it: every consuming repo runs
 * the same script, and an upgrade is a regenerate rather than nine hand-edits.
 */

/** Repo-relative paths the hook owns. */
export const HOOK_SCRIPT_PATH = '.claude/hooks/duro-catalog.sh'
export const HOOK_SETTINGS_PATH = '.claude/settings.json'
export const HOOK_CACHE_PATH = '.claude/.duro-session.cache'
/**
 * `duro doctor --session` output, and the key of the files it was computed
 * from. Named under HOOK_CACHE_PATH so the existing ignore glob covers them —
 * no .gitignore drift in the repos already wired.
 */
export const HOOK_DOCTOR_CACHE_PATH = `${HOOK_CACHE_PATH}.doctor`
/**
 * Glob, not the bare path: the script stages the fetch through
 * "<cache>.tmp", and a session-start hook killed mid-npx leaves that behind.
 */
export const HOOK_CACHE_IGNORE = `${HOOK_CACHE_PATH}*`
/** Repo-specific caveats, appended by the hook and never touched by install. */
export const HOOK_NOTES_PATH = '.claude/duro-hook.local.md'

/** What settings.json runs. Also the marker install matches on. */
export const HOOK_COMMAND = `sh ${HOOK_SCRIPT_PATH}`

/**
 * Floor for the npx pin. Raise this only when the session payload needs
 * newer CLI behavior — a floating pin keeps patch releases from showing up
 * as --check drift, but a floor left behind a major means no consumer ever
 * sees what the payload gained (1.2.0 pinned every repo out of 2.x).
 * 3.0.0: the SCREENS section and the /duro-mockup pointer.
 * 3.4.0: duro doctor --session.
 */
export const HOOK_MIN_CLI = '3.4.0'

export const HOOK_SCRIPT = `#!/bin/sh
# Duro design-system session bootstrap — GENERATED by \`duro hook install\`.
# Regenerate: npx -y @duro-app/cli hook install   (--check verifies it in CI)
#
# Injects the consult-first preamble plus the component catalog into agent
# context at SessionStart, so "check the design system before building UI" is
# ambient context instead of a step an agent has to remember. Then runs
# \`duro doctor\`, which says nothing unless this repo's build wiring flattens
# the components' styles.
#
# Do not hand-edit. Repo-specific caveats go in
# ${HOOK_NOTES_PATH} — appended below, and left alone by regeneration.
cache="${HOOK_CACHE_PATH}"
notes="${HOOK_NOTES_PATH}"
doctor="${HOOK_DOCTOR_CACHE_PATH}"

# npx resolution dominates session start; the catalog only changes on upgrade.
if [ ! -s "$cache" ] || [ -n "$(find "$cache" -mtime +7 2>/dev/null)" ]; then
  if npx -y @duro-app/cli@^${HOOK_MIN_CLI} hook session-start >"$cache.tmp" 2>/dev/null; then
    mv "$cache.tmp" "$cache"
  else
    rm -f "$cache.tmp"
  fi
fi

# Offline with no cache yet: stay silent rather than fail the session.
if [ -s "$cache" ]; then
  cat "$cache"
  if [ -s "$notes" ]; then
    echo
    cat "$notes"
  fi
fi

# duro doctor reads build config, entries and stylesheets. Re-run it when one
# of those changes rather than on a timer, so an edit shows up next session
# and a healthy repo only pays for npx after touching its config.
key=$(find . -maxdepth 4 \\( -name node_modules -o -name .git -o -name dist -o -name build \\) -prune -o \\
  -type f \\( -name package.json -o -name pnpm-workspace.yaml -o -name '*.css' -o -name 'vite*' \\
  -o -name 'babel*' -o -name '.babelrc*' -o -name '*.babel.*' -o -name 'postcss*' \\
  -o -name 'root.tsx' -o -name 'main.tsx' -o -name 'index.tsx' \\) -exec cksum {} + 2>/dev/null |
  sort | cksum)
if [ "$key" != "$(cat "$doctor.key" 2>/dev/null)" ]; then
  if npx -y @duro-app/cli@^${HOOK_MIN_CLI} doctor --session >"$doctor.tmp" 2>/dev/null; then
    mv "$doctor.tmp" "$doctor"
    echo "$key" >"$doctor.key"
  else
    rm -f "$doctor.tmp"
  fi
fi
if [ -s "$doctor" ]; then
  echo
  cat "$doctor"
fi
`

export const GITIGNORE_BLOCK = `# Duro session-hook cache (duro hook install)\n${HOOK_CACHE_IGNORE}\n`
