/**
 * The generated Claude Code SessionStart hook, and the wiring it needs.
 *
 * Kept as data (not prose in a README) so `duro hook install` can write it and
 * `duro hook install --check` can byte-compare it: every consuming repo runs
 * the same script, and an upgrade is a regenerate rather than nine hand-edits.
 */

/** Repo-relative paths the hook owns. */
export const HOOK_SCRIPT_PATH = '.claude/hooks/duro-catalog.sh'
export const HOOK_SETTINGS_PATH = '.claude/settings.json'
export const HOOK_CACHE_PATH = '.claude/.duro-session.cache'
/**
 * Glob, not the bare path: the script stages the fetch through
 * "<cache>.tmp", and a session-start hook killed mid-npx leaves that behind.
 */
export const HOOK_CACHE_IGNORE = `${HOOK_CACHE_PATH}*`
/** Repo-specific caveats, appended by the hook and never touched by install. */
export const HOOK_NOTES_PATH = '.claude/duro-hook.local.md'

/** What settings.json runs. Also the marker install matches on. */
export const HOOK_COMMAND = `sh ${HOOK_SCRIPT_PATH}`

/**
 * Floor for the npx pin. Raise this only when the session payload needs
 * newer CLI behavior — a floating pin keeps patch releases from showing up
 * as --check drift, but a floor left behind a major means no consumer ever
 * sees what the payload gained (1.2.0 pinned every repo out of 2.x).
 * 3.0.0: the SCREENS section and the /duro-mockup pointer.
 */
export const HOOK_MIN_CLI = '3.0.0'

export const HOOK_SCRIPT = `#!/bin/sh
# Duro design-system session bootstrap — GENERATED by \`duro hook install\`.
# Regenerate: npx -y @duro-app/cli hook install   (--check verifies it in CI)
#
# Injects the consult-first preamble plus the component catalog into agent
# context at SessionStart, so "check the design system before building UI" is
# ambient context instead of a step an agent has to remember.
#
# Do not hand-edit. Repo-specific caveats go in
# ${HOOK_NOTES_PATH} — appended below, and left alone by regeneration.
cache="${HOOK_CACHE_PATH}"
notes="${HOOK_NOTES_PATH}"

# npx resolution dominates session start; the catalog only changes on upgrade.
if [ ! -s "$cache" ] || [ -n "$(find "$cache" -mtime +7 2>/dev/null)" ]; then
  if npx -y @duro-app/cli@^${HOOK_MIN_CLI} hook session-start >"$cache.tmp" 2>/dev/null; then
    mv "$cache.tmp" "$cache"
  else
    rm -f "$cache.tmp"
  fi
fi

# Offline with no cache yet: stay silent rather than fail the session.
[ -s "$cache" ] || exit 0
cat "$cache"

if [ -s "$notes" ]; then
  echo
  cat "$notes"
fi
`

export const GITIGNORE_BLOCK = `# Duro session-hook cache (duro hook install)\n${HOOK_CACHE_IGNORE}\n`
