/**
 * The generated Claude Code skill that runs a screen from mockup to PR
 * without leaving the design system.
 *
 * Kept as data (not prose in a README) so `duro skill install` can write it
 * and `duro skill install --check` can byte-compare it: every consuming repo
 * runs the same workflow, and a change to it is a regenerate rather than
 * N hand-edits. Repo-specific notes go in SKILL_NOTES_PATH, which the skill
 * tells the agent to read and which regeneration never touches.
 */

/** Repo-relative paths the install owns. */
export const SKILL_DIR = '.claude/skills/duro-mockup'
export const SKILL_PATH = `${SKILL_DIR}/SKILL.md`
/** Repo-specific caveats, read by the skill and never touched by install. */
export const SKILL_NOTES_PATH = '.claude/duro-mockup.local.md'

/**
 * Floor for the npx pin inside the skill. `duro mockup` landed in 3.0.0. A
 * floating pin keeps patch releases from showing up as --check drift.
 */
export const SKILL_MIN_CLI = '3.0.0'

const DURO = `npx -y @duro-app/cli@^${SKILL_MIN_CLI}`

export const SKILL = `---
name: duro-mockup
description: Take a new screen from mockup directions to an implemented, verified PR without leaving the Duro design system. Use whenever the user asks for a screen, a page, a UI proposal, mockups, or "show me options" in a repo that consumes @duro-app/ui.
---

# duro-mockup

GENERATED by \`duro skill install\` — do not hand-edit. Regenerate:
\`${DURO} skill install\` (\`--check\` verifies it in CI). Repo-specific notes
live in \`${SKILL_NOTES_PATH}\`; read it if it exists.

Standing rule (fleet decision \`ui.mockup-handoff\`): a mockup is written in
the design system's own vocabulary, and the direction the user picks is a
contract. What binds: layout, hierarchy, states, the \`data-duro\` component
map and the token names. What does not bind: the artboard's pixel geometry.

**This overrides the \`design\` skill's step 0.** That skill says to lift
resolved values from the real stylesheets. Here you never write a resolved
value: every colour, spacing, radius, font, shadow and duration is a
\`var(--duro-*)\` from the seeded token block, and every element a person can
act on carries \`data-duro="<Component>"\`. The rest of the \`design\` skill
(artboard shape, \`seed-canvas.mjs\`, the canvas Artifact) still applies.

## Args

- \`propose <screen>\` — seed 2–4 direction artboards, check them, publish the canvas.
- \`implement <screen> <direction>\` — build the picked direction from its component map.
- \`prove <route>\` — screenshot the built route and assemble the PR section.
- no args — infer the stage from what exists under \`docs/mockups/<screen>/\`.

## propose

\`\`\`bash
${DURO} mockup seed --out docs/mockups/<screen> --name Main          # direction A
${DURO} mockup seed --out docs/mockups/<screen> --name <Direction>   # B, C, …
\`\`\`

- \`<screen>\` is kebab-case (\`approval-gates\`). Artboards are committed with
  the PR — never leave them in a scratch directory; a session scratchpad is
  garbage-collected and the canvas URL would be the only surviving artefact.
- Author each artboard inside the seeded \`<style>\` and root div. Colours,
  spacing, radii, type, shadows and motion come only from the token block;
  widths, heights and positions are yours. Every button, row, chip, tab,
  input, link, table and dialog — whatever element it is drawn as — carries
  \`data-duro="<Component>"\` or \`data-duro="<Component>.<Part>"\`, using names
  from \`${DURO} list components\`. Notes for the implementer go after the
  name: \`data-duro="Button variant=primary"\`.
- Start from a recipe when one fits the screen shape (\`${DURO} list recipes\`
  — admin-detail-page, split-pane, page-with-sidenav, settings-page, …) and
  say so in the artboard's header comment; a hand-rolled layout needs a reason.
- Gate before publishing:

\`\`\`bash
${DURO} mockup check docs/mockups/<screen>/*.dc.html
\`\`\`

  Exit 1 lists \`file:line rule: message\`. Fix every finding; do not publish
  an artboard that fails. Then seed the canvas with the \`design\` skill's
  helper (it lives under the current Claude Code version's bundled-skills
  directory — locate it, never hardcode the path) and publish the Artifact.
- Ask the user to pick a direction. Record the answer as
  \`<canvas URL> · direction <X>\` — it goes in the PR.
- If the user edits an artboard in the canvas editor, its property panel
  writes literals back over \`var()\` by design. Re-extract and run
  \`mockup check\` again, but treat those findings as advisory: the authored
  file in \`docs/mockups/\` is the contract, the canvas is the review surface.

## implement

- Read the picked artboard. Its \`data-duro\` attributes ARE the component
  list: for each one, \`${DURO} <Component>\` (or the \`duro_ds_lookup\` MCP
  tool) gives props and usage. Do not substitute a hand-rolled element for a
  named component; if a named component does not fit, say so and propose the
  design-system change rather than working around it.
- Tokens map one to one: \`var(--duro-spacing-md)\` is \`spacing.md\` from
  \`@duro-app/tokens/tokens/spacing.css\`, \`--duro-color-bg-card\` is
  \`colors.bgCard\`, \`--duro-radius-sm\` is \`radii.sm\`, \`--duro-typography-*\`
  and \`--duro-type-scale-*\` are \`typography\`/\`typeScale\`, \`--duro-shadow-*\`
  is \`shadows\`, \`--duro-duration-*\`/\`--duro-easing-*\` are \`duration\`/\`easing\`.
  A media query on \`768px\` is \`breakpoints.md\` from
  \`@duro-app/tokens/tokens/breakpoints.css\`. The lint config refuses the raw
  value, so write the token the first time.
- Layout comes from a recipe before a grid: \`${DURO} <recipe> --source-only\`.
- Geometry in the artboard is a sketch. Match its hierarchy and states, not
  its pixel widths.

## prove

- Run the app, load the route in a real browser (Chrome MCP), and take a
  screenshot at the artboard's width (1120px) in the artboard's theme.
- The PR body carries, under \`## Mockup\`: the canvas URL and direction, the
  path \`docs/mockups/<screen>/\`, and the artboard next to the live screenshot.
  A PR that touches no screen writes \`Mockup: none\` instead. CI checks for
  one or the other.
- If the screenshot and the artboard disagree on hierarchy or states, that is
  a finding to fix, not a caption to write.
`
